services:
  payment-api:
    image: 670173257019.dkr.ecr.ap-southeast-2.amazonaws.com/payment-app:latest
    container_name: payment-api
    restart: always
    ports:
      - "3000:3000"

    environment:
      DB_HOST: payment-db.czqamc00o19t.ap-southeast-2.rds.amazonaws.com
      DB_USER: adminUser
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: payments
      DB_PORT: 5432