name: CI/CD Pipeline - ECS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configure AWS credentials
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Login to ECR
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build Docker image
      - name: Build image
        run: |
          docker build -t payment-app .

      # 5. Tag image with ECR registry
      - name: Tag image for ECR
        run: |
          docker tag payment-app:latest \
          ${{ steps.login-ecr.outputs.registry }}/payment-app:latest

      # 6. Push image to ECR
      - name: Push image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/payment-app:latest

      # 7. Update ECS task definition
      - name: Update ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: payment-api
          image: ${{ steps.login-ecr.outputs.registry }}/payment-app:latest

      # 8. Deploy to ECS
      - name: Deploy to ECS Fargate
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: payment-task-service-mvo1x0x5
          cluster: payment-cluster
          force-new-deployment: true